version: 2.1
jobs:
  build-securedrop-client:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run: 
          name: Install Debian packaging dependencies
          command: make install-deps

      - run:
          name: Download wheels and sources
          command: make fetch-wheels

      - run:
          name: Clone the repository to be packaged
          command: |
            mkdir ~/packaging && cd ~/packaging
            git clone https://github.com/freedomofpress/securedrop-client.git

      - run:
          name: Get latest tag for the project and make a source tarball
          command: |
            cd ~/packaging/securedrop-client
            export LATEST_TAG="$(git describe --tags $(git rev-list --tags --max-count=1))"
            # Enable access to this env var in subsequent run steps
            echo $LATEST_TAG > ~/packaging/sd_client_version
            echo 'export LATEST_TAG=$(cat ~/packaging/sd_client_version)' >> $BASH_ENV
            # Create tarball
            git checkout $LATEST_TAG
            python3 setup.py sdist

      - run:
          name: Build securedrop-client debian package
          command: |
            export PKG_PATH=~/packaging/securedrop-client/dist/securedrop-client-$LATEST_TAG.tar.gz
            export PKG_VERSION=$LATEST_TAG
            export PKG_NAME="securedrop-client"
            ./scripts/build-debianpackage
            ls ~/debbuild/packaging/securedrop-client/

workflows:
  build-debian-packages:
    jobs:
      - build-securedrop-client