#!/bin/bash
# Wrapper script to create/update the requirements.txt
# It finds the correct project directory from the `PKG_DIR` envirionment variable.
#

set -e
set -u
set -o pipefail

if [[ -z "${PKG_DIR:-}" ]]; then
    echo "Set PKG_DIR of the project.";
    exit 1
fi

cd $PKG_DIR

# Now create a copy of the requirements.txt file so we can
# replace the hashes (which points to the source tarballs and wheels
# from PSF's PyPI) with build-requirements.txt which will (eventually)
# contain hashes pointing to the wheels on FPF's PyPI.
cp requirements.txt build-requirements.txt
